apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadastrocliente-frontend
  labels:
    app: cadastrocliente-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadastrocliente-frontend
  template:
    metadata:
      labels:
        app: cadastrocliente-frontend
    spec:
      containers:
      - name: cadastrocliente-frontend
        # Lembre-se de alterar para o endereço correto da sua imagem no registry (ex: dockerhub, AWS ECR)
        image: southamerica-east1-docker.pkg.dev/viratech-1010-508115/cadastrocliente-front-repo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
